-- =============================================
-- SCRIPT SETUP HOÀN CHỈNH CHO NGƯỜI MỚI
-- Chạy script này theo thứ tự để setup toàn bộ hệ thống
-- =============================================

PRINT '============================================='
PRINT 'SETUP ETL PIPELINE - CHẠY THEO THỨ TỰ'
PRINT '============================================='
PRINT ''
PRINT '⚠️ LƯU Ý: Chạy các file SQL theo thứ tự sau:'
PRINT ''
PRINT 'BƯỚC 1: Tạo databases'
PRINT '  → Chạy: 01_Create_Database.sql'
PRINT ''
PRINT 'BƯỚC 2: Tạo schema Data Warehouse'
PRINT '  → Chạy: 02_Create_DW_Schema.sql'
PRINT ''
PRINT 'BƯỚC 3: Tạo schema Data Mart'
PRINT '  → Chạy: 03_Create_DM_Schema.sql'
PRINT ''
PRINT 'BƯỚC 4: Populate DimDate'
PRINT '  → Chạy: 04_Populate_DimDate.sql'
PRINT ''
PRINT 'BƯỚC 5: Tạo stored procedure cho Data Warehouse'
PRINT '  → Chạy: 05_ELT_Load_DW.sql'
PRINT '  ✅ File này đã được fix:'
PRINT '     - MERGE để xử lý duplicate MacAddress'
PRINT '     - ProcessDate = NULL xử lý TẤT CẢ dữ liệu'
PRINT ''
PRINT 'BƯỚC 6: Tạo stored procedure cho Data Mart'
PRINT '  → Chạy: 06_ELT_Load_DM.sql'
PRINT '  ✅ File này đã được fix:'
PRINT '     - ProcessDate = NULL xử lý TẤT CẢ dữ liệu'
PRINT '     - Không tham chiếu đến Fact_MediaReport'
PRINT ''
PRINT 'BƯỚC 7: (Tùy chọn) Tạo scheduler'
PRINT '  → Chạy: 07_Create_Scheduler.sql'
PRINT ''
PRINT '============================================='
PRINT 'SAU KHI SETUP XONG:'
PRINT '============================================='
PRINT '1. Chạy ETL pipeline: python run_full_etl.py'
PRINT '2. Kiểm tra dữ liệu:'
PRINT '   USE DW_MediaAnalytics'
PRINT '   SELECT COUNT(*) FROM DimContract'
PRINT '   SELECT COUNT(*) FROM DimDevice'
PRINT '   SELECT COUNT(*) FROM FactViewingSession'
PRINT ''
PRINT '3. Xem tài liệu: Solution.md để biết các lỗi đã được fix'
PRINT '============================================='
GO
